name: Convert Markdown to PDF and Commit to Repo

on:
  push:
    paths:
      - "RESUME.md"
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest  # Using latest available Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensure authentication for pushing

      - name: Install Pandoc
        run: sudo apt update && sudo apt install -y pandoc

      - name: Get current date
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Convert Markdown to PDF
        run: pandoc RESUME.md -o RESUME-${{ env.DATE }}.pdf --pdf-engine=xelatex

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add RESUME-${{ env.DATE }}.pdf
          git commit -m "Automated update: Convert RESUME.md to RESUME-${{ env.DATE }}.pdf [skip ci]" || exit 0
          git push origin HEAD:main
