name: Convert Markdown to PDF and Commit to Repo

on:
  push:
    paths:
      - "RESUME.md"
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest  # Use latest stable Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensure authentication for pushing

      - name: Install Node.js, Puppeteer Dependencies & md-to-pdf
        run: |
          sudo apt update
          sudo apt install -y nodejs npm libx11-xcb1 libxtst6 libxrandr2 libasound2
          npm install -g md-to-pdf

      - name: Get current date
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Convert Markdown to PDF using md-to-pdf with --no-sandbox
        run: |
          md-to-pdf RESUME.md --launch-options.args="--no-sandbox --disable-setuid-sandbox"

      - name: Move generated PDF to the pdf/ folder
        run: |
          mkdir -p pdf
          mv RESUME.pdf pdf/RESUME-${{ env.DATE }}.pdf

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add pdf/RESUME-${{ env.DATE }}.pdf
          git commit -m "Automated update: Convert RESUME.md to pdf/RESUME-${{ env.DATE }}.pdf [skip ci]" || exit 0
          git push origin HEAD:main
