name: Convert Markdown to PDF and Commit to Repo

on:
  push:
    branches:
      - "main"
    paths:
      - "RESUME.md"
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest  # Use the latest stable Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensure authentication for pushing

      - name: Install Node.js, Chromium, and Dependencies
        run: |
          sudo apt update
          sudo apt install -y nodejs npm chromium-browser libx11-xcb1 libxtst6 libxrandr2

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf puppeteer

      - name: Get current date
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Set Puppeteer Environment Variables
        run: |
          echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV

      - name: Convert Markdown to PDF using md-to-pdf
        run: md-to-pdf RESUME.md

      - name: Move generated PDF to the pdf/ folder
        run: |
          mkdir -p pdf
          mv RESUME.pdf pdf/RESUME-${{ env.DATE }}.pdf

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add pdf/RESUME-${{ env.DATE }}.pdf
          git commit -m "Automated update: Convert RESUME.md to pdf/RESUME-${{ env.DATE }}.pdf [skip ci]" || exit 0
          git push origin HEAD:main
          
      - name: Install mailsend-go (if Gmail credentials exist)
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          if [[ -n "$GMAIL_USERNAME" && -n "$GMAIL_PASSWORD" ]]; then
            echo "Installing mailsend-go..."
            curl -L https://github.com/muquit/mailsend-go/releases/download/v1.0.10/mailsend-go_1.0.10_linux_amd64.tar.gz -o mailsend-go.tar.gz
            tar -xzf mailsend-go.tar.gz
            sudo mv mailsend-go /usr/local/bin/
          else
            echo "Skipping mailsend-go installation: No Gmail credentials found."
          fi

      - name: Send Email with PDF Attachment (if Gmail credentials exist)
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          if [[ -n "$GMAIL_USERNAME" && -n "$GMAIL_PASSWORD" ]]; then
            echo "Sending email with resume PDF..."
            mailsend-go \
            -smtp smtp.gmail.com \
            -port 587 \
            -auth \
            -user "$GMAIL_USERNAME" \
            -pass "$GMAIL_PASSWORD" \
            -from "$GMAIL_USERNAME" \
            -to "$GMAIL_USERNAME" \
            -sub "Updated Resume - ${{ env.DATE }}" \
            -msg "Attached is your latest resume in PDF format, generated automatically." \
            -attach "pdf/RESUME-${{ env.DATE }}.pdf"
          else
            echo "Skipping email: No Gmail credentials found."
          fi