name: Convert Markdown to PDF and Commit to Repo

on:
  push:
    paths:
      - "RESUME.md"
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-22.04  # Use a stable Ubuntu version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures authentication for pushing

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc texlive-xetex fonts-dejavu fonts-noto fonts-noto-color-emoji

      - name: Get current date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Convert Markdown to PDF
        run: |
          pandoc RESUME.md -o RESUME.pdf --pdf-engine=xelatex \
          -V mainfont="DejaVu Sans" \
          -V sansfont="Noto Sans" \
          -V monofont="DejaVu Sans Mono" \
          -V mathfont="Latin Modern Math" \
          -V fontfamily="Noto Sans" \
          -V geometry:margin=1in

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add RESUME.pdf
          git commit -m "Automated update: Convert RESUME.md to RESUME.pdf [skip ci]" || exit 0
          git push origin HEAD:main
